"""Container types and SSH config formatting for cmlxc.

Defines the base ``Container`` handle and its subclasses
``RelayContainer`` and ``BuilderContainer``.
All interaction with Incus containers goes through these types.
"""

import shlex
import subprocess
import textwrap
import time

# Incus custom configuration labels (user.localchat-*):
# - LABEL_KEY: Boolean 'true' for containers managed by cmlxc.
# - LABEL_DOMAIN: The primary DNS domain assigned to the container.
# - LABEL_DEPLOY_DRIVER: The deployment driver ('cmdeploy' or 'madmail').
# - LABEL_DEPLOYED_AT: ISO timestamp of the last successful deployment.

LABEL_KEY = "user.localchat-managed"
LABEL_DOMAIN = "user.localchat-domain"
LABEL_DEPLOY_DRIVER = "user.localchat-deploy-driver"
LABEL_DEPLOYED_AT = "user.localchat-deployed-at"
LABEL_DEPLOY_SOURCE = "user.localchat-deploy-source"

# SSH and Domain config
SSH_KEY_NAME = "id_localchat"
DOMAIN_SUFFIX = ".localchat"

# Image names
UPSTREAM_IMAGE = "images:debian/12"
BASE_IMAGE_ALIAS = "localchat-base"

# Builder container
BUILDER_CONTAINER_NAME = "builder-localchat"
BUILDER_DOMAIN = "builder.localchat"

# DNS container
DNS_NS = "ns.localchat"
DNS_CONTAINER_NAME = "ns-localchat"


class DNSConfigurationError(Exception):
    """Raised on DNS reachability or response failure."""


class SetupError(Exception):
    """User-facing error raised when a pre-condition is not met."""


def _extract_ip(net_data, family="inet"):
    for iface_name, iface in net_data.items():
        if iface_name == "lo":
            continue
        for addr in iface.get("addresses", []):
            if addr["family"] == family and addr["scope"] == "global":
                return addr["address"]
    return None


def format_ssh_config(containers, key_path):
    """Format an SSH config block for the given container dicts."""
    lines = ["# Auto-generated by cmlxc -- do not edit\n"]
    for c in containers:
        ip = c.get("ip")
        if not ip:
            continue
        hosts = [c["name"]]
        domain = c.get("domain", "")
        if domain and domain != c["name"]:
            hosts.append(domain)
            short = domain.split(".")[0]
            if short and short not in hosts:
                hosts.append(short)
            # also allow short name without the leading underscore
            bare = short.lstrip("_")
            if bare and bare not in hosts:
                hosts.append(bare)
        lines.append(f"\nHost {' '.join(hosts)}\n")
        lines.append(f"    Hostname {ip}\n")
        lines.append("    User root\n")
        lines.append(f"    IdentityFile {key_path}\n")
        lines.append("    IdentitiesOnly yes\n")
        lines.append("    StrictHostKeyChecking accept-new\n")
        lines.append("    UserKnownHostsFile /dev/null\n")
        lines.append("    LogLevel ERROR\n")
    return "".join(lines)


class Container:
    """Base container handle wrapping incus interactions."""

    def __init__(self, incus, name, domain=None):
        self.incus = incus
        self.out = incus.out
        self.name = name
        self.shortname = name.removesuffix("-localchat")
        self.domain = domain or f"{name}{DOMAIN_SUFFIX}"
        self.ipv4 = None
        self.ipv6 = None

    def bash(self, script, check=True):
        """Execute bash script in container and return stdout."""
        script = textwrap.dedent(script).strip()
        cmd = ["exec", self.name, "--", "bash", "-ec", script]
        return self.incus.run_output(cmd, check=check)

    def run_cmd(self, *args, check=True):
        """Run command in container and return stdout."""
        return self.incus.run_output(
            ["exec", self.name, "--", *args],
            check=check,
        )

    def start(self):
        self.incus.run(["start", self.name])

    def stop(self, force=False):
        cmd = ["stop", self.name]
        if force:
            cmd.append("--force")
        self.incus.run(cmd, check=False)

    def launch(self, image_candidates=None):
        """Launch from the base image or a provided candidate."""
        if image_candidates is None:
            image_candidates = [BASE_IMAGE_ALIAS]

        image = self.incus.find_image(image_candidates)
        if not image:
            raise RuntimeError(
                f"No suitable image found in {image_candidates}. "
                "Ensure the base image exists."
            )
        self.out.print(f"  Launching from '{image}' image ...")
        cfg = []
        cfg += ("-c", f"{LABEL_KEY}=true")
        cfg += ("-c", f"{LABEL_DOMAIN}={self.domain}")
        self.incus.run(["launch", image, self.name, *cfg])
        return image

    @property
    def is_running(self):
        """Check if the container is currently running."""
        data = self.incus.run_json(["list", self.name], check=False) or []
        return bool(data) and data[0].get("status") == "Running"

    @property
    def is_ipv6_disabled(self):
        """Check if IPv6 is disabled in the kernel (sysctl)."""
        result = self.run_cmd(
            "sysctl", "-n", "net.ipv6.conf.all.disable_ipv6", check=False
        )
        return result == "1"

    def ensure(self, ipv4_only=False, image_candidates=None):
        data = self.incus.run_json(["list", self.name], check=False) or []

        existing = [c for c in data if c["name"] == self.name]
        if existing:
            if existing[0]["status"] != "Running":
                self.start()
        else:
            self.launch(image_candidates=image_candidates)
        self.wait_ready(expect_ipv6=not ipv4_only)

    def destroy(self):
        self.stop(force=True)
        self.incus.run(["delete", self.name, "--force"], check=False)

    def push_file_content(self, dest_path, content, mode="644"):
        """Write content to dest_path in container."""
        content = textwrap.dedent(content).strip() + "\n"
        self.incus.run(
            [
                "file",
                "push",
                "--uid=0",
                "--gid=0",
                f"--mode={mode}",
                "-",
                f"{self.name}{dest_path}",
            ],
            input=content,
        )

    def get_deploy_state(self):
        """Return deploy state dict or *None* if not deployed."""
        data = self.incus.run_json(["list", self.name], check=False)
        if not data or not isinstance(data, list):
            return None
        config = data[0].get("config", {})
        driver = config.get(LABEL_DEPLOY_DRIVER)
        if not driver:
            return None
        return {
            "driver": driver,
            "timestamp": config.get(LABEL_DEPLOYED_AT, "Unknown"),
            "source": config.get(LABEL_DEPLOY_SOURCE),
        }

    def write_deploy_state(self, deploy_driver, source=None):
        """Record that a deployment of *deploy_driver* occurred."""
        now = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
        source_desc = source.description if source else None
        cmd = [
            "config",
            "set",
            self.name,
            f"{LABEL_DEPLOY_DRIVER}={deploy_driver}",
            f"{LABEL_DEPLOYED_AT}={now}",
        ]
        if source_desc:
            cmd.append(f"{LABEL_DEPLOY_SOURCE}={source_desc}")
        self.incus.run(cmd)
        return {"driver": deploy_driver, "timestamp": now, "source": source_desc}

    def check_deploy_lock(self, deploy_driver):
        state = self.get_deploy_state()
        if state is None:
            return
        if state["driver"] != deploy_driver:
            raise SetupError(
                f"Previously deployed with {state['driver']!r} "
                f"(at {state['timestamp']}). "
                f"Run 'cmlxc destroy {self.shortname}' first, then redeploy "
                f"with {deploy_driver!r}."
            )

    def wait_ready(self, timeout=60, expect_ipv6=False):
        deadline = time.time() + timeout
        last_msg_time = time.time()
        while time.time() < deadline:
            data = self.incus.run_json(
                ["list", self.name],
                check=False,
            )
            if data and data[0].get("status") == "Running":
                net = data[0].get("state", {}).get("network", {})
                self.ipv4 = _extract_ip(net, "inet")
                self.ipv6 = _extract_ip(net, "inet6")
                if self.ipv4 and (not expect_ipv6 or self.ipv6):
                    return

                if time.time() - last_msg_time > 5:
                    msg = "Waiting for network..."
                    if not self.ipv4:
                        msg += " (no IPv4 yet)"
                    elif expect_ipv6 and not self.ipv6:
                        msg += " (IPv4 ready, waiting for IPv6)"
                    self.out.print(f"  {msg}")
                    last_msg_time = time.time()

            time.sleep(1)

        msg = f"Container {self.name!r} did not become ready within {timeout}s"
        if not self.ipv4:
            msg += " (No IPv4 address obtained)"
        elif expect_ipv6 and not self.ipv6:
            msg += " (Has IPv4, but NO IPv6 address obtained)"
        raise TimeoutError(msg)


class RelayContainer(Container):
    """Container handle for a chatmail relay."""

    def __init__(self, incus, name):
        super().__init__(
            incus,
            f"{name}-localchat",
            domain=f"_{name}{DOMAIN_SUFFIX}",
        )

    @property
    def driver_name(self):
        state = self.get_deploy_state()
        return state["driver"] if state else None

    def get_repo_path(self, driver_name=None):
        """Return the absolute path to the repo in the builder container."""
        driver = driver_name or self.driver_name
        if not driver:
            raise ValueError(f"No driver known for container {self.shortname!r}")
        return f"/root/relays/{driver}-{self.shortname}"

    def get_venv_path(self, driver_name=None):
        """Return the absolute path to the venv in the builder container."""
        return f"{self.get_repo_path(driver_name)}/venv"

    def destroy(self):
        """Destroy current relay container and its checkout in the builder."""
        state = self.get_deploy_state()
        if state:
            driver = state.get("driver")
            if driver:
                repo_path = self.get_repo_path(driver)
                self.incus.run(
                    ["exec", BUILDER_CONTAINER_NAME, "--", "rm", "-rf", repo_path],
                    check=False,
                )
        super().destroy()

    def launch(self, image_candidates=None):
        image = super().launch(image_candidates=image_candidates)
        # Re-inject the current SSH key; cached images may have a stale one.
        pub_key = self.incus.ssh_key_path.with_suffix(".pub").read_text().strip()
        self.bash(f"""
            mkdir -p /root/.ssh && chmod 700 /root/.ssh
            echo '{pub_key}' > /root/.ssh/authorized_keys
            chmod 600 /root/.ssh/authorized_keys
            rm -f /etc/chatmail-version
            rm -f /etc/sysctl.d/99-disable-ipv6.conf
            sysctl -w net.ipv6.conf.all.disable_ipv6=0 2>/dev/null || true
            sysctl -w net.ipv6.conf.default.disable_ipv6=0 2>/dev/null || true
        """)
        return image

    def ensure(self, ipv4_only=False, image_candidates=None):
        out = self.out

        out.green(f"Ensuring container {self.name!r} ({self.domain}) ...")

        data = self.incus.run_json(["list", self.name], check=False) or []
        existing = [c for c in data if c["name"] == self.name]
        if existing:
            if existing[0]["status"] != "Running":
                self.out.print(f"  Starting container {self.name!r} ...")
                self.start()
            if not ipv4_only:
                self.enable_ipv6()
        else:
            self.launch(image_candidates=image_candidates)
        self.wait_ready(expect_ipv6=not ipv4_only)
        if ipv4_only:
            self.disable_ipv6()

        sub = out.new_prefixed_out()
        sub.print("Configuring container hostname ...")
        self.bash(f"echo '{self.name}' > /etc/hostname")
        sub.print(f"IPv4 {self.ipv4}, IPv6 {self.ipv6}")
        sub.green(f"Container {self.name!r} ready: {self.domain} -> {self.ipv4}")

        out.green("Writing ssh-config ...")
        ssh_cfg = self.incus.write_ssh_config()
        sub.print(f"{ssh_cfg}")

        sub.print(f"Verifying SSH to {self.name} via ssh-config ...")
        if self.verify_ssh(ssh_cfg):
            sub.print(f"SSH OK: ssh -F {self.incus.ssh_config_path} {self.domain}")
        else:
            sub.red(f"WARNING: SSH verification failed for {self.name}")

        if not self.incus.check_ssh_include():
            sub.green(
                "\n(Optional) To use containers from any SSH client,"
                " add to ~/.ssh/config:"
            )
            sub.green(f"    Include {self.incus.ssh_config_path}")

    def disable_ipv6(self):
        # incus provides net.* virtualization for LXC containers so that
        # these sysctls only affect the container's network namespace.
        self.bash("""
            sysctl -w net.ipv6.conf.all.disable_ipv6=1
            sysctl -w net.ipv6.conf.default.disable_ipv6=1
        """)
        self.push_file_content(
            "/etc/sysctl.d/99-disable-ipv6.conf",
            """
            net.ipv6.conf.all.disable_ipv6=1
            net.ipv6.conf.default.disable_ipv6=1
            """,
        )

    def enable_ipv6(self):
        self.bash("""
            rm -f /etc/sysctl.d/99-disable-ipv6.conf
            sysctl -w net.ipv6.conf.all.disable_ipv6=0
            sysctl -w net.ipv6.conf.default.disable_ipv6=0
        """)

    def verify_ssh(self, ssh_config):
        cmd = ["ssh", "-F", str(ssh_config), "-o", "ConnectTimeout=60"]
        cmd += [f"root@{self.domain}", "hostname"]
        return (
            subprocess.run(
                cmd,
                capture_output=True,
                timeout=60,
                check=False,
            ).returncode
            == 0
        )

    def configure_dns(self, dns_ip):
        self.bash(f"""
            systemctl disable --now systemd-resolved 2>/dev/null || true
            rm -f /etc/resolv.conf
            printf 'nameserver {dns_ip}\\n' >/etc/resolv.conf
            mkdir -p /etc/unbound/unbound.conf.d
        """)
        ip6_line = "  do-ip6: no" if not self.ipv6 else ""
        self.push_file_content(
            "/etc/unbound/unbound.conf.d/localchat-forward.conf",
            f"""
            server:
              domain-insecure: "localchat"
            {ip6_line}

            forward-zone:
              name: "localchat"
              forward-addr: {dns_ip}
            """,
        )
        self.bash("systemctl restart unbound || true")
        self._wait_dns_reachable(dns_ip)

    def _wait_dns_reachable(self, dns_ip, timeout=10):
        if self.bash("which dig", check=False) is None:
            self.bash(
                "DEBIAN_FRONTEND=noninteractive apt-get install -y dnsutils 2>/dev/null"
            )
        deadline = time.time() + timeout
        while time.time() < deadline:
            result = self.bash(
                f"dig @{dns_ip} . SOA +short +time=1 +tries=1",
                check=False,
            )
            if result and result.strip():
                return
            time.sleep(0.5)
        raise DNSConfigurationError(
            f"DNS at {dns_ip} not reachable from {self.name} after {timeout}s"
        )


class BuilderContainer(Container):
    """Container for building, deploying, and testing chatmail relays."""

    def __init__(self, incus):
        super().__init__(incus, BUILDER_CONTAINER_NAME, domain=BUILDER_DOMAIN)

    def configure_dns(self, dns_ip):
        self.bash(f"""
            systemctl disable --now systemd-resolved 2>/dev/null || true
            rm -f /etc/resolv.conf
            printf 'nameserver {dns_ip}\\n' >/etc/resolv.conf
        """)

    def install_deps(self):
        self.bash("""
            if ! command -v git >/dev/null 2>&1 || ! command -v make >/dev/null 2>&1; then
                apt-get -o DPkg::Lock::Timeout=60 update
                DEBIAN_FRONTEND=noninteractive apt-get install -y \
                    python3-venv git gcc make python3-dev rsync
                apt-get clean && rm -rf /var/lib/apt/lists/*
            fi
            if [ ! -d /root/minitest-venv ]; then
                python3 -m venv /root/minitest-venv
                /root/minitest-venv/bin/pip install \
                    pytest \
                    pytest-xdist \
                    deltachat-rpc-client \
                    deltachat-rpc-server \
                    imap-tools \
                    requests \
                    python-dotenv \
                    cryptography
                rm -rf /root/.cache/pip
            fi
        """)

    def sync_to(self, local_path, remote_path):
        self.incus.run(["exec", self.name, "--", "mkdir", "-p", remote_path])

        lpath = shlex.quote(str(local_path))
        rpath = shlex.quote(str(remote_path))
        excludes = " ".join(
            f"--exclude='{d}'" for d in ["venv", ".tox", "__pycache__", ".ruff_cache"]
        )
        cmd = (
            f"tar -C {lpath} {excludes} -cf - . | "
            f"incus --quiet exec {self.name} -- tar -C {rpath} -xf -"
        )

        if self.out.verbosity >= 1:
            self.out.print(f"$ {cmd}")

        res = subprocess.run(
            cmd,
            shell=True,
            capture_output=True,
            text=True,
            executable="/bin/bash",
            check=False,
        )

        if res.returncode != 0:
            raise RuntimeError(
                f"Failed to sync {local_path} to {self.name}:{remote_path}\n"
                f"Error: {res.stderr.strip()}"
            )

    def setup_repo(self, dest, out, source):
        name = dest.rsplit("/", 1)[-1]
        self.bash(f"rm -rf {dest}")
        out.print(f"  Initial clone of {name} ...")
        self.bash(f"git clone {source.url} {dest}")

    def get_repo_status(self, repo_path):
        """Return a one-line string describing the git repo at repo_path."""
        if self.bash(f"test -d {repo_path}", check=False) is None:
            return None
        commit = self.bash(
            f"cd {repo_path} && git log -1 --format='%h %s' --abbrev=12",
            check=False,
        )
        if commit:
            return commit.strip()
        return "synced from host"

    def sync_mini_tests(self, test_dir):
        self.sync_to(test_dir, "/root/minitest")

    def run_mini_tests(self, relay1, relay2, out):
        args = f"--relay1 {relay1}"
        if relay2:
            args += f" --relay2 {relay2}"
        cmd = (
            f"incus exec {self.name} --"
            f" bash -c 'source /root/minitest-venv/bin/activate &&"
            f" cd /root/minitest &&"
            f" export PYTHONPATH=. &&"
            f" pytest . -v {args}'"
        )
        return out.shell(cmd)

    def init_ssh(self):
        """Push the SSH key and set up Include in the builder."""
        key = self.incus.ssh_key_path
        self.bash("mkdir -p /root/.ssh/config.d && chmod 700 /root/.ssh")
        self.incus.run(
            ["file", "push", str(key), f"{self.name}/root/.ssh/id_localchat"]
        )
        self.bash("chown root:root /root/.ssh/id_localchat")
        self.bash("chmod 600 /root/.ssh/id_localchat")
        self.bash(
            "printf 'Include /root/.ssh/config.d/*\\n\\n"
            "Host *\\n"
            "  IdentityFile /root/.ssh/id_localchat\\n"
            "  StrictHostKeyChecking accept-new\\n"
            "  UserKnownHostsFile /dev/null\\n"
            "  LogLevel ERROR\\n'"
            " > /root/.ssh/config"
        )

    def write_relay_ssh_config(self, ct):
        """Write an ssh-config.d file for a single relay container."""
        if not ct.ipv4:
            ct.wait_ready()
        entry = {"name": ct.name, "ip": ct.ipv4, "domain": ct.domain}
        content = format_ssh_config([entry], "/root/.ssh/id_localchat")
        dest = f"/root/.ssh/config.d/{ct.name}"
        self.push_file_content(dest, content, mode="600")

        # prune old ssh host entries
        files = self.bash("ls /root/.ssh/config.d/ 2>/dev/null")
        managed = {c["name"] for c in self.incus.list_managed()}
        for name in set(files.split()).difference(managed):
            self.bash(f"rm -f /root/.ssh/config.d/{name}")

    def scp_to_relay(self, src_path, relay_ip, dest_path):
        self.bash(
            f"scp -o StrictHostKeyChecking=accept-new"
            f" -o UserKnownHostsFile=/dev/null"
            f" -i /root/.ssh/id_localchat"
            f" {src_path} root@{relay_ip}:{dest_path}"
        )

    def cleanup(self):
        """Remove ephemeral checkouts and caches to minimize image size."""
        self.bash("""
            # Remove all ephemeral relay checkouts
            rm -rf /root/relays/*
            
            # Remove all package manager caches
            rm -rf /root/.cache/*
            rm -rf /root/.npm
            rm -rf /root/.bun
            
            # Clean up apt specifically just in case
            apt-get clean
            rm -rf /var/lib/apt/lists/*
        """)


class DNSContainer(Container):
    """Handle for PowerDNS name server container."""

    def __init__(self, incus):
        super().__init__(incus, DNS_CONTAINER_NAME, domain=DNS_NS)

    def pdnsutil(self, *args, check=True):
        """Run ``pdnsutil <args>`` inside the DNS container."""
        return self.run_cmd("pdnsutil", *args, check=check)

    def restart_services(self):
        self.bash("""
            systemctl restart pdns
            systemctl restart pdns-recursor
        """)
        self._wait_dns_ready()

    def _wait_dns_ready(self, timeout=60):
        deadline = time.time() + timeout
        while time.time() < deadline:
            result = self.bash(
                "dig @127.0.0.1 . SOA +short +time=1 +tries=1",
                check=False,
            )
            if result and result.strip():
                return
            time.sleep(0.5)
        raise DNSConfigurationError(f"DNS recursor not answering after {timeout}s")

    def ensure(self, **kwargs):
        super().ensure(**kwargs)
        self._install_powerdns()
        self.incus.run(
            ["network", "set", "incusbr0", "dns.mode=none"],
            check=False,
        )
        self.incus.run(
            ["network", "set", "incusbr0", f"raw.dnsmasq=dhcp-option=6,{self.ipv4}"],
            check=False,
        )

    def destroy(self):
        super().destroy()
        self.incus.run(["network", "unset", "incusbr0", "dns.mode"], check=False)
        self.incus.run(["network", "unset", "incusbr0", "raw.dnsmasq"], check=False)

    def _install_powerdns(self):
        if self.run_cmd("which", "pdns_server", check=False) is not None:
            return

        host_ns = self.incus.get_host_nameservers()
        ns_lines = "\n".join(f"nameserver {n}" for n in host_ns)

        self.bash(f"""
            systemctl disable --now systemd-resolved 2>/dev/null || true
            rm -f /etc/resolv.conf
            printf '{ns_lines}\\n' > /etc/resolv.conf

            # Block automatic service startup during package installation
            printf '#!/bin/sh\\nexit 101\\n' > /usr/sbin/policy-rc.d
            chmod +x /usr/sbin/policy-rc.d

            apt-get -o DPkg::Lock::Timeout=60 update
            DEBIAN_FRONTEND=noninteractive apt-get install -y \
                pdns-server pdns-backend-sqlite3 sqlite3 pdns-recursor dnsutils
            apt-get clean && rm -rf /var/lib/apt/lists/*

            # Remove the startup block
            rm /usr/sbin/policy-rc.d

            systemctl stop pdns pdns-recursor || true
            rm -f /etc/powerdns/pdns.d/*
            mkdir -p /var/lib/powerdns
            sqlite3 /var/lib/powerdns/pdns.sqlite3 < /usr/share/pdns-backend-sqlite3/schema/schema.sqlite3.sql
            chown -R pdns:pdns /var/lib/powerdns
        """)

        self.push_file_content(
            "/etc/powerdns/pdns.conf",
            """
            launch=gsqlite3
            gsqlite3-database=/var/lib/powerdns/pdns.sqlite3
            local-address=127.0.0.1
            local-port=5353
            """,
        )

        self.push_file_content(
            "/etc/powerdns/recursor.conf",
            """
            local-address=0.0.0.0
            local-port=53
            forward-zones=localchat=127.0.0.1:5353
            allow-from=0.0.0.0/0
            dont-query=
            dnssec=off
            """,
        )

        self.bash("""
            systemctl start pdns
            systemctl start pdns-recursor
            echo 'nameserver 127.0.0.1' > /etc/resolv.conf
        """)
        self._wait_dns_ready()

    def set_dns_records(self, zone, text):
        # Ensure zone exists or load-zone will fail
        self.pdnsutil("create-zone", zone, f"ns.{zone}", check=False)

        # PowerDNS load-zone usually expects a SOA and NS record at the apex.
        # It also needs a glue record (A) for the nameserver itself.
        if "SOA" not in text:
            self.wait_ready()
            serial = str(int(time.time()))
            soa = f"{zone}. 3600 IN SOA ns.{zone}. hostmaster.{zone}. {serial} 3600 900 604800 300\n"
            ns = f"{zone}. 3600 IN NS ns.{zone}.\n"
            glue = f"ns.{zone}. 3600 IN A {self.ipv4}\n"
            text = soa + ns + glue + text

        # Push content to container and load into PowerDNS
        tmp_zone = f"/tmp/zonefile-{zone}"
        self.incus.run(
            ["exec", self.name, "--", "bash", "-c", f"cat > {tmp_zone}"],
            input=text,
        )
        self.pdnsutil("load-zone", zone, tmp_zone)
        self.restart_services()
