"""Incus container management for chatmail relay testing.

Manages container lifecycles, image caching,
and deployment state tracking
using Incus-specific ``user.localchat-*`` labels.

The base image (``localchat-base``) has SSH and Python
pre-installed and is used as a template for all containers.

Deployment drivers (``cmdeploy`` and ``madmail``) are tracked
via labels to prevent conflicting configurations --
a container must be destroyed before switching drivers.
"""

import ipaddress
import json
import shlex
import shutil
import subprocess
import textwrap
import time
from pathlib import Path

from xdg_base_dirs import xdg_config_home

# Incus custom configuration labels (user.localchat-*):
# - LABEL_KEY: Boolean 'true' for containers managed by cmlxc.
# - LABEL_DOMAIN: The primary DNS domain assigned to the container.
# - LABEL_DEPLOY_DRIVER: The tool used for the last deployment ('cmdeploy' or 'madmail').
# - LABEL_DEPLOYED_AT: ISO timestamp of the last successful deployment.

LABEL_KEY = "user.localchat-managed"
LABEL_DOMAIN = "user.localchat-domain"
LABEL_DEPLOY_DRIVER = "user.localchat-deploy-driver"
LABEL_DEPLOYED_AT = "user.localchat-deployed-at"

# SSH and Domain config
SSH_KEY_NAME = "id_localchat"
DOMAIN_SUFFIX = ".localchat"

# Image names
UPSTREAM_IMAGE = "images:debian/12"
BASE_IMAGE_ALIAS = "localchat-base"
RELAY_IMAGE_ALIAS = "localchat-relay"

# Container and DNS names
BASE_SETUP_NAME = "localchat-base-setup"
DNS_NS = "ns.localchat"
DNS_CONTAINER_NAME = "ns-localchat"
BUILDER_CONTAINER_NAME = "builder-localchat"
BUILDER_DOMAIN = "builder.localchat"


class DNSConfigurationError(Exception):
    """Raised on DNS reachability or response failure."""


class DeployConflictError(Exception):
    """Raised when deploying with a different type than previously used."""


CMDEPLOY = "cmdeploy"
MADMAIL = "madmail"


def _extract_ip(net_data, family="inet"):
    """Extract first global IP of *family* from incus data."""
    for iface_name, iface in net_data.items():
        if iface_name == "lo":
            continue
        for addr in iface.get("addresses", []):
            if addr["family"] == family and addr["scope"] == "global":
                return addr["address"]
    return None


def _is_ip_address(s):
    """Return True if *s* looks like an IPv4 or IPv6 address."""
    try:
        ipaddress.ip_address(s)
        return True
    except ValueError:
        return False


def format_ssh_config(containers, key_path):
    """Format an SSH config block for the given container dicts."""
    lines = ["# Auto-generated by cmlxc -- do not edit\n"]
    for c in containers:
        ip = c.get("ip")
        if not ip:
            continue
        hosts = [c["name"]]
        domain = c.get("domain", "")
        if domain and domain != c["name"]:
            hosts.append(domain)
            short = domain.split(".")[0]
            if short and short not in hosts:
                hosts.append(short)
        lines.append(f"\nHost {' '.join(hosts)}\n")
        lines.append(f"    Hostname {ip}\n")
        lines.append("    User root\n")
        lines.append(f"    IdentityFile {key_path}\n")
        lines.append("    IdentitiesOnly yes\n")
        lines.append("    StrictHostKeyChecking accept-new\n")
        lines.append("    UserKnownHostsFile /dev/null\n")
        lines.append("    LogLevel ERROR\n")
    return "".join(lines)


class Incus:
    """Helper for Incus container operations."""

    def __init__(self, out):
        self.out = out
        self.config_dir = xdg_config_home() / "cmlxc"
        self.config_dir.mkdir(parents=True, exist_ok=True)
        self.ssh_key_path = self.config_dir / SSH_KEY_NAME
        if not self.ssh_key_path.exists():
            cmd = ["ssh-keygen", "-t", "ed25519"]
            cmd += ["-f", str(self.ssh_key_path), "-N", "", "-C", "localchat"]
            subprocess.run(
                cmd,
                check=True,
            )
        self.ssh_config_path = self.config_dir / "ssh-config"

    def write_ssh_config(self):
        """Write ``ssh-config`` mapping all containers to their IPs."""
        containers = self.list_managed()
        text = format_ssh_config(containers, self.ssh_key_path)
        self.ssh_config_path.write_text(text)
        return self.ssh_config_path

    def check_ssh_include(self):
        """Check if ~/.ssh/config includes our ssh-config."""
        user_ssh_config = Path.home() / ".ssh" / "config"
        if not user_ssh_config.exists():
            return False
        lines = user_ssh_config.read_text().splitlines()
        target = f"include {self.ssh_config_path}".lower()
        return any(line.strip().lower() == target for line in lines)

    def get_host_nameservers(self):
        """Return upstream nameservers found on the host."""
        ns = []
        for path in ["/run/systemd/resolve/resolv.conf", "/etc/resolv.conf"]:
            p = Path(path)
            if p.exists():
                for line in p.read_text().splitlines():
                    if line.strip().startswith("nameserver "):
                        addr = line.split()[1]
                        if addr not in ("127.0.0.1", "127.0.0.53", "::1"):
                            if addr not in ns:
                                ns.append(addr)
                if ns:
                    break
        return ns

    def run(self, args, check=True, input=None):
        """Run an incus command and return result."""
        cmd = ["incus", "--quiet"]
        cmd += list(args)
        sub = self.out.new_prefixed_out("  ")

        if sub.verbosity >= 1:
            sub.print(f"$ {' '.join(cmd)}")

        proc = subprocess.Popen(
            cmd,
            text=True,
            stdin=subprocess.PIPE if input is not None else subprocess.DEVNULL,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
        try:
            if input is not None:
                stdout, stderr = proc.communicate(input=input)
            else:
                stdout, stderr = proc.communicate()
        except KeyboardInterrupt:
            proc.terminate()
            try:
                proc.wait(timeout=3)
            except subprocess.TimeoutExpired:
                proc.kill()
            raise
        ret = proc.returncode
        if sub.verbosity >= 2:
            for line in stdout.splitlines():
                sub.print(f"  > {line}")
        if check and ret != 0:
            full_output = stdout + stderr
            for line in full_output.splitlines():
                if sub.verbosity < 1:
                    sub.red(line)
            raise subprocess.CalledProcessError(ret, cmd, output=stdout, stderr=stderr)

        return subprocess.CompletedProcess(cmd, ret, stdout=stdout, stderr=stderr)

    def run_json(self, args, check=True):
        """Run incus command and return parsed JSON."""
        result = self.run(
            list(args) + ["--format=json"],
            check=check,
        )
        if result.returncode != 0:
            return None
        return json.loads(result.stdout)

    def run_output(self, args, check=True):
        """Run incus command and return stripped stdout."""
        result = self.run(args, check=check)
        if result.returncode != 0:
            return None
        return result.stdout.strip()

    def find_image(self, aliases):
        """Return the first alias from *aliases* that exists, else None."""
        images = self.run_json(["image", "list"], check=False) or []
        existing = {a.get("name") for img in images for a in img.get("aliases", [])}
        for alias in aliases:
            if alias in existing:
                return alias
        return None

    def delete_images(self):
        """Delete all localchat-related cached images."""
        for img in self.run_json(["image", "list"]):
            aliases = [a["name"] for a in img.get("aliases", [])]
            is_localchat = any(a.startswith("localchat-") for a in aliases)
            if is_localchat or not aliases:
                fp = img["fingerprint"]
                self.run(["image", "delete", fp], check=False)

    @staticmethod
    def get_container_name(name):
        """Return the full container name for a given short name."""
        if name.endswith("-localchat"):
            return name
        return f"{name}-localchat"

    def list_managed(self):
        """Return list of dicts with name, ip, ipv6, domain, status."""
        containers = []
        for ct in self.run_json(["list"]):
            config = ct.get("config", {})
            if config.get(LABEL_KEY) != "true":
                continue
            name = ct["name"]
            state = ct.get("state", {})
            net = state.get("network") or {}
            containers.append(
                {
                    "name": name,
                    "ip": _extract_ip(net, "inet"),
                    "ipv6": _extract_ip(net, "inet6"),
                    "domain": config.get(LABEL_DOMAIN, f"{name}{DOMAIN_SUFFIX}"),
                    "status": ct.get("status", "Unknown"),
                }
            )
        return containers

    def ensure_base_image(self):
        """Build and cache base image with openssh."""
        if self.find_image([BASE_IMAGE_ALIAS]):
            self.out.print(f"  Base image '{BASE_IMAGE_ALIAS}' already cached.")
            return BASE_IMAGE_ALIAS

        self.out.print("  Building base image (one-time setup) ...")

        self.run(["delete", BASE_SETUP_NAME, "--force"], check=False)
        self.run(["image", "delete", BASE_IMAGE_ALIAS], check=False)
        self.run(["launch", UPSTREAM_IMAGE, BASE_SETUP_NAME])

        ct = Container(self, BASE_SETUP_NAME)
        ct.wait_ready()

        key_path = self.ssh_key_path
        pub_key = key_path.with_suffix(".pub").read_text().strip()
        host_ns = self.get_host_nameservers()
        ns_lines = "\n".join(f"nameserver {n}" for n in host_ns)
        ct.bash(f"""
            printf '{ns_lines}\n' > /etc/resolv.conf
            apt-get -o DPkg::Lock::Timeout=60 update
            DEBIAN_FRONTEND=noninteractive apt-get purge -y unattended-upgrades
            DEBIAN_FRONTEND=noninteractive apt-get install -y \
                openssh-server python3 build-essential python3-dev
            systemctl enable ssh
            apt-get clean
            mkdir -p /root/.ssh
            chmod 700 /root/.ssh
            echo '{pub_key}' > /root/.ssh/authorized_keys
            chmod 600 /root/.ssh/authorized_keys
            # Incus containers only get ULA IPv6 addresses which cannot
            # route to the internet.  Prefer IPv4 for outbound connections
            # so that curl/wget/apt don't hang trying IPv6 first.
            echo 'precedence ::ffff:0:0/96  100' >> /etc/gai.conf
        """)

        self.run(["stop", BASE_SETUP_NAME])
        self.run(["publish", BASE_SETUP_NAME, f"--alias={BASE_IMAGE_ALIAS}"])
        self.run(["delete", BASE_SETUP_NAME, "--force"])
        self.out.print(f"  Base image '{BASE_IMAGE_ALIAS}' ready.")
        return BASE_IMAGE_ALIAS

    def get_container(self, name):
        """Return a DNSContainer, ContainerBuilder, or RelayContainer."""
        if name == DNS_CONTAINER_NAME:
            return DNSContainer(self)
        if name == BUILDER_CONTAINER_NAME:
            return ContainerBuilder(self)
        return RelayContainer(self, name.removesuffix("-localchat"))


class Container:
    """Base container handle wrapping incus interactions."""

    def __init__(self, incus, name, domain=None):
        self.incus = incus
        self.out = incus.out
        self.name = name
        self.domain = domain or f"{name}{DOMAIN_SUFFIX}"
        self.ipv4 = None
        self.ipv6 = None

    def bash(self, script, check=True):
        """Execute bash script in container and return stdout."""
        script = textwrap.dedent(script).strip()
        cmd = ["exec", self.name, "--", "bash", "-ec", script]
        return self.incus.run_output(cmd, check=check)

    def run_cmd(self, *args, check=True):
        """Run command in container and return stdout."""
        return self.incus.run_output(
            ["exec", self.name, "--", *args],
            check=check,
        )

    def start(self):
        self.incus.run(["start", self.name])

    def stop(self, force=False):
        cmd = ["stop", self.name]
        if force:
            cmd.append("--force")
        self.incus.run(cmd, check=False)

    def launch(self):
        """Launch from the base image."""
        image = self.incus.find_image([BASE_IMAGE_ALIAS])
        if not image:
            raise RuntimeError(
                f"No base image '{BASE_IMAGE_ALIAS}' found. "
                "Call ensure_base_image() before launching containers."
            )
        self.out.print(f"  Launching from '{image}' image ...")
        cfg = []
        cfg += ("-c", f"{LABEL_KEY}=true")
        cfg += ("-c", f"{LABEL_DOMAIN}={self.domain}")
        self.incus.run(["launch", image, self.name, *cfg])
        return image

    @property
    def is_running(self):
        """Check if the container is currently running."""
        data = self.incus.run_json(["list", self.name], check=False) or []
        return bool(data) and data[0].get("status") == "Running"

    @property
    def is_ipv6_disabled(self):
        """Check if IPv6 is disabled in the kernel (sysctl)."""
        return self.run_cmd("sysctl", "-n", "net.ipv6.conf.all.disable_ipv6") == "1"

    def ensure(self, ipv4_only=False, image_preference=None):
        data = self.incus.run_json(["list", self.name], check=False) or []

        existing = [c for c in data if c["name"] == self.name]
        if existing:
            if existing[0]["status"] != "Running":
                self.start()
        else:
            self.launch()
        self.wait_ready(expect_ipv6=not ipv4_only)

    def destroy(self):
        self.stop(force=True)
        self.incus.run(["delete", self.name, "--force"], check=False)

    def push_file_content(self, dest_path, content):
        """Write content to dest_path in container."""
        content = textwrap.dedent(content).strip() + "\n"
        self.incus.run(
            ["file", "push", "-", f"{self.name}{dest_path}"],
            input=content,
        )
        self.bash(f"chmod 644 {dest_path}")

    def get_deploy_state(self):
        """Return deploy state dict or *None* if not deployed."""
        data = self.incus.run_json(["list", self.name], check=False)
        if not data or not isinstance(data, list):
            return None
        config = data[0].get("config", {})
        driver = config.get(LABEL_DEPLOY_DRIVER)
        if not driver:
            return None
        return {
            "driver": driver,
            "timestamp": config.get(LABEL_DEPLOYED_AT, "Unknown"),
        }

    def write_deploy_state(self, deploy_driver):
        """Record that a deployment of *deploy_driver* occurred."""
        now = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
        self.incus.run(
            [
                "config",
                "set",
                self.name,
                f"{LABEL_DEPLOY_DRIVER}={deploy_driver}",
                f"{LABEL_DEPLOYED_AT}={now}",
            ]
        )
        return {"driver": deploy_driver, "timestamp": now}

    def check_deploy_lock(self, deploy_driver):
        state = self.get_deploy_state()
        if state is None:
            return
        if state["driver"] != deploy_driver:
            # Use short name (sname) if available (RelayContainer), else name
            sname = getattr(self, "sname", self.name)
            raise DeployConflictError(
                f"Previously deployed with {state['driver']!r} "
                f"(at {state['timestamp']}). "
                f"Run 'cmlxc destroy {sname}' first, then redeploy "
                f"with {deploy_driver!r}."
            )

    def wait_ready(self, timeout=60, expect_ipv6=False):
        deadline = time.time() + timeout
        while time.time() < deadline:
            data = self.incus.run_json(
                ["list", self.name],
                check=False,
            )
            if data and data[0].get("status") == "Running":
                net = data[0].get("state", {}).get("network", {})
                self.ipv4 = _extract_ip(net, "inet")
                self.ipv6 = _extract_ip(net, "inet6")
                if self.ipv4 and (not expect_ipv6 or self.ipv6):
                    return
            time.sleep(1)
        raise TimeoutError(
            f"Container {self.name!r} did not become ready within {timeout}s"
        )


class RelayContainer(Container):
    """Container handle for a chatmail relay."""

    def __init__(self, incus, name):
        super().__init__(
            incus,
            f"{name}-localchat",
            domain=f"_{name}{DOMAIN_SUFFIX}",
        )
        self.sname = name
        self.relay_dir = incus.config_dir / name
        self.ini = self.relay_dir / "chatmail.ini"
        self.zone = self.relay_dir / "chatmail.zone"

    def launch(self, image_preference=None):
        if image_preference == "base":
            candidates = [BASE_IMAGE_ALIAS]
        else:
            candidates = [RELAY_IMAGE_ALIAS, BASE_IMAGE_ALIAS]
        image = self.incus.find_image(candidates)
        if not image:
            raise RuntimeError(
                f"No base image '{BASE_IMAGE_ALIAS}' found. "
                "Call ensure_base_image() before launching containers."
            )
        self.out.print(f"  Launching from '{image}' image ...")
        cfg = []
        cfg += ("-c", f"{LABEL_KEY}=true")
        cfg += ("-c", f"{LABEL_DOMAIN}={self.domain}")
        self.incus.run(["launch", image, self.name, *cfg])
        # Re-inject the current SSH key; cached images may have a stale one.
        pub_key = self.incus.ssh_key_path.with_suffix(".pub").read_text().strip()
        self.bash(f"""
            mkdir -p /root/.ssh && chmod 700 /root/.ssh
            echo '{pub_key}' > /root/.ssh/authorized_keys
            chmod 600 /root/.ssh/authorized_keys
            rm -f /etc/chatmail-version
            rm -f /etc/sysctl.d/99-disable-ipv6.conf
            sysctl -w net.ipv6.conf.all.disable_ipv6=0 2>/dev/null || true
            sysctl -w net.ipv6.conf.default.disable_ipv6=0 2>/dev/null || true
        """)
        return image

    def ensure(self, ipv4_only=False, image_preference=None):
        data = self.incus.run_json(["list", self.name], check=False) or []
        existing = [c for c in data if c["name"] == self.name]
        if existing:
            if existing[0]["status"] != "Running":
                self.start()
        else:
            self.launch(image_preference=image_preference)
        self.wait_ready(expect_ipv6=not ipv4_only)
        if ipv4_only:
            self.disable_ipv6()

    def destroy(self):
        super().destroy()
        if self.relay_dir.exists():
            shutil.rmtree(self.relay_dir)

    def disable_ipv6(self):
        # incus provides net.* virtualization for LXC containers so that
        # these sysctls only affect the container's network namespace.
        self.bash("""
            sysctl -w net.ipv6.conf.all.disable_ipv6=1
            sysctl -w net.ipv6.conf.default.disable_ipv6=1
        """)
        self.push_file_content(
            "/etc/sysctl.d/99-disable-ipv6.conf",
            """
            net.ipv6.conf.all.disable_ipv6=1
            net.ipv6.conf.default.disable_ipv6=1
            """,
        )

    # Services that must not auto-start from a cached image because
    # they would use stale DNS or network configuration.
    _CACHED_DISABLE_SERVICES = [
        "postfix",
        "dovecot",
        "unbound",
        "opendkim",
        "nginx",
        "filtermail",
        "filtermail-incoming",
        "fcgiwrap",
    ]

    def publish_as_relay_image(self):
        if self.incus.find_image([RELAY_IMAGE_ALIAS]):
            return
        self.out.print(
            f"  Locally caching {self.name!r} as '{RELAY_IMAGE_ALIAS}' image ..."
        )
        units = " ".join(f"{s}.service" for s in self._CACHED_DISABLE_SERVICES)
        self.bash("cp /etc/resolv.conf /tmp/resolv.conf.bak")
        self.bash(f"systemctl disable --now {units}")
        self.bash("rm -f /etc/resolv.conf")
        self.incus.run(
            ["publish", self.name, f"--alias={RELAY_IMAGE_ALIAS}", "--force"]
        )
        # Restore DNS and re-enable services on the running container
        self.bash("cp /tmp/resolv.conf.bak /etc/resolv.conf")
        self.bash(f"systemctl enable --now {units}")
        self.wait_ready()
        self.out.print(f"  Relay image '{RELAY_IMAGE_ALIAS}' ready.")

    def verify_ssh(self, ssh_config):
        cmd = ["ssh", "-F", str(ssh_config), "-o", "ConnectTimeout=60"]
        cmd += [f"root@{self.domain}", "hostname"]
        return (
            subprocess.run(
                cmd,
                capture_output=True,
                timeout=60,
                check=False,
            ).returncode
            == 0
        )

    def configure_dns(self, dns_ip):
        self.bash(f"""
            systemctl disable --now systemd-resolved 2>/dev/null || true
            rm -f /etc/resolv.conf
            printf 'nameserver {dns_ip}\\n' >/etc/resolv.conf
            mkdir -p /etc/unbound/unbound.conf.d
        """)
        ip6_line = "  do-ip6: no" if not self.ipv6 else ""
        self.push_file_content(
            "/etc/unbound/unbound.conf.d/localchat-forward.conf",
            f"""
            server:
              domain-insecure: "localchat"
            {ip6_line}

            forward-zone:
              name: "localchat"
              forward-addr: {dns_ip}
            """,
        )
        self.bash("systemctl restart unbound || true")
        self._wait_dns_reachable(dns_ip)

    def _wait_dns_reachable(self, dns_ip, timeout=10):
        if self.bash("which dig", check=False) is None:
            self.bash(
                "DEBIAN_FRONTEND=noninteractive apt-get install -y dnsutils 2>/dev/null"
            )
        deadline = time.time() + timeout
        while time.time() < deadline:
            result = self.bash(
                f"dig @{dns_ip} . SOA +short +time=1 +tries=1",
                check=False,
            )
            if result and result.strip():
                return
            time.sleep(0.5)
        raise DNSConfigurationError(
            f"DNS at {dns_ip} not reachable from {self.name} after {timeout}s"
        )


class ContainerBuilder(Container):
    """Container for building, deploying, and testing chatmail relays."""

    def __init__(self, incus):
        super().__init__(incus, BUILDER_CONTAINER_NAME, domain=BUILDER_DOMAIN)

    def configure_dns(self, dns_ip):
        self.bash(f"""
            systemctl disable --now systemd-resolved 2>/dev/null || true
            rm -f /etc/resolv.conf
            printf 'nameserver {dns_ip}\\n' >/etc/resolv.conf
        """)

    def install_deps(self):
        self.bash("""
            apt-get -o DPkg::Lock::Timeout=60 update
            DEBIAN_FRONTEND=noninteractive apt-get install -y \
                python3-venv git build-essential python3-dev rsync
            python3 -m venv /root/minitest-venv
            /root/minitest-venv/bin/pip install \\
                pytest \\
                pytest-xdist \\
                deltachat-rpc-client \\
                deltachat-rpc-server \\
                imap-tools \\
                requests
        """)

    def sync_to(self, local_path, remote_path):
        self.incus.run(["exec", self.name, "--", "mkdir", "-p", remote_path])

        lpath = shlex.quote(str(local_path))
        rpath = shlex.quote(str(remote_path))
        cmd = (
            f"tar -C {lpath} -cf - . | "
            f"incus --quiet exec {self.name} -- tar -C {rpath} -xf -"
        )

        if self.out.verbosity >= 1:
            self.out.print(f"$ {cmd}")

        res = subprocess.run(
            cmd,
            shell=True,
            capture_output=True,
            text=True,
            executable="/bin/bash",
            check=False,
        )

        if res.returncode != 0:
            raise RuntimeError(
                f"Failed to sync {local_path} to {self.name}:{remote_path}\n"
                f"Error: {res.stderr.strip()}"
            )

    def setup_repo(self, dest, out, url=None, local_path=None):
        name = dest.rsplit("/", 1)[-1]
        if local_path:
            out.print(f"  Syncing {name} from {local_path} ...")
            self.sync_to(local_path, dest)
        else:
            out.print(f"  Cloning {name} repository ...")
            self.bash(f"rm -rf {dest}")
            self.bash(f"git clone --depth=1 {url} {dest}")
        self.bash(f"git config --global --add safe.directory {dest}")

    def install_relay_deps(self):
        self.bash("""
            if [ ! -d /root/cmdeploy-venv ]; then
                python3 -m venv /root/cmdeploy-venv
            fi
            /root/cmdeploy-venv/bin/pip install \
                -e /root/relay/chatmaild \
                -e /root/relay/cmdeploy
        """)

    def sync_mini_tests(self, test_dir):
        self.sync_to(test_dir, "/root/minitest")

    def run_mini_tests(self, pytest_args, out):
        args_str = " ".join(pytest_args)
        cmd = (
            f"incus exec {self.name} --"
            f" bash -c 'source /root/minitest-venv/bin/activate &&"
            f" cd /root/minitest &&"
            f" export PYTHONPATH=. &&"
            f" pytest . -v {args_str}'"
        )
        return out.shell(cmd)

    def push_chatmail_ini(self, ini_path):
        self.incus.run(
            ["file", "push", str(ini_path), f"{self.name}/root/chatmail.ini"]
        )

    def setup_ssh(self, relay_containers):
        key = self.incus.ssh_key_path
        self.bash("mkdir -p /root/.ssh && chmod 700 /root/.ssh")
        self.incus.run(
            ["file", "push", str(key), f"{self.name}/root/.ssh/id_localchat"]
        )
        self.bash("chown root:root /root/.ssh/id_localchat")
        self.bash("chmod 600 /root/.ssh/id_localchat")

        lines = []
        for ct in relay_containers:
            if not ct.ipv4:
                ct.wait_ready()
            lines.append(f"Host {ct.domain} {ct.name}")
            lines.append(f"    Hostname {ct.ipv4}")
            lines.append("    User root")
            lines.append("    IdentityFile /root/.ssh/id_localchat")
            lines.append("    IdentitiesOnly yes")
            lines.append("    StrictHostKeyChecking accept-new")
            lines.append("    UserKnownHostsFile /dev/null")
            lines.append("    LogLevel ERROR")
            lines.append("")
        config_content = "\n".join(lines)
        self.bash(f"""\
            cat > /root/.ssh/config << 'SSHEOF'
{config_content}
SSHEOF
            chown root:root /root/.ssh/config
            chmod 600 /root/.ssh/config
        """)

    def run_cmdeploy_tests(self, pytest_args, out, env=None):
        env_exports = "export CHATMAIL_INI=/root/chatmail.ini"
        for k, v in (env or {}).items():
            env_exports += f" && export {k}={v}"
        args_str = " ".join(pytest_args)
        cmd = (
            f"incus exec {self.name} --"
            f" bash -c '"
            f"{env_exports} &&"
            f" source /root/cmdeploy-venv/bin/activate &&"
            f" cd /root/relay &&"
            f" pytest cmdeploy/src/ -n4 -rs -x -v --durations=5 {args_str}'"
        )
        return out.shell(cmd)

    def scp_to_relay(self, src_path, relay_ip, dest_path):
        self.bash(
            f"scp -o StrictHostKeyChecking=accept-new"
            f" -o UserKnownHostsFile=/dev/null"
            f" -i /root/.ssh/id_localchat"
            f" {src_path} root@{relay_ip}:{dest_path}"
        )


class DNSContainer(Container):
    """Handle for PowerDNS name server container."""

    def __init__(self, incus):
        super().__init__(incus, DNS_CONTAINER_NAME, domain=DNS_NS)

    def pdnsutil(self, *args, check=True):
        """Run ``pdnsutil <args>`` inside the DNS container."""
        return self.run_cmd("pdnsutil", *args, check=check)

    def replace_rrset(self, zone, name, rtype, ttl, rdata):
        """Shortcut for ``pdnsutil replace-rrset``."""
        self.pdnsutil("replace-rrset", zone, name, rtype, ttl, rdata)

    def restart_services(self):
        self.bash("""
            systemctl restart pdns
            systemctl restart pdns-recursor
        """)
        self._wait_dns_ready()

    def _wait_dns_ready(self, timeout=60):
        deadline = time.time() + timeout
        while time.time() < deadline:
            result = self.bash(
                "dig @127.0.0.1 . SOA +short +time=1 +tries=1",
                check=False,
            )
            if result and result.strip():
                return
            time.sleep(0.5)
        raise DNSConfigurationError(f"DNS recursor not answering after {timeout}s")

    def ensure(self, **kwargs):
        super().ensure(**kwargs)
        self._install_powerdns()
        self.incus.run(
            ["network", "set", "incusbr0", "dns.mode=none"],
            check=False,
        )
        self.incus.run(
            ["network", "set", "incusbr0", f"raw.dnsmasq=dhcp-option=6,{self.ipv4}"],
            check=False,
        )

    def destroy(self):
        super().destroy()
        self.incus.run(["network", "unset", "incusbr0", "dns.mode"], check=False)
        self.incus.run(["network", "unset", "incusbr0", "raw.dnsmasq"], check=False)

    def _install_powerdns(self):
        if self.run_cmd("which", "pdns_server", check=False) is not None:
            return

        host_ns = self.incus.get_host_nameservers()
        ns_lines = "\n".join(f"nameserver {n}" for n in host_ns)

        self.bash(f"""
            systemctl disable --now systemd-resolved 2>/dev/null || true
            rm -f /etc/resolv.conf
            printf '{ns_lines}\n' > /etc/resolv.conf

            # Block automatic service startup during package installation
            printf '#!/bin/sh\\nexit 101\\n' > /usr/sbin/policy-rc.d
            chmod +x /usr/sbin/policy-rc.d

            apt-get -o DPkg::Lock::Timeout=60 update
            DEBIAN_FRONTEND=noninteractive apt-get install -y \
                pdns-server pdns-backend-sqlite3 sqlite3 pdns-recursor dnsutils

            # Remove the startup block
            rm /usr/sbin/policy-rc.d

            systemctl stop pdns pdns-recursor || true
            rm -f /etc/powerdns/pdns.d/*
            mkdir -p /var/lib/powerdns
            sqlite3 /var/lib/powerdns/pdns.sqlite3 < /usr/share/pdns-backend-sqlite3/schema/schema.sqlite3.sql
            chown -R pdns:pdns /var/lib/powerdns
        """)

        self.push_file_content(
            "/etc/powerdns/pdns.conf",
            """
            launch=gsqlite3
            gsqlite3-database=/var/lib/powerdns/pdns.sqlite3
            local-address=127.0.0.1
            local-port=5353
            """,
        )

        self.push_file_content(
            "/etc/powerdns/recursor.conf",
            """
            local-address=0.0.0.0
            local-port=53
            forward-zones=localchat=127.0.0.1:5353
            allow-from=0.0.0.0/0
            dont-query=
            dnssec=off
            """,
        )

        self.bash("""
            systemctl start pdns
            systemctl start pdns-recursor
            echo 'nameserver 127.0.0.1' > /etc/resolv.conf
        """)
        self._wait_dns_ready()

    def reset_dns_records(self, dns_ip, domains):
        for d in domains:
            domain = d["domain"]
            ip = d["ip"]
            self.out.print(f"  {domain} -> {ip}")

            # Delete and recreate zone fresh (removes stale records)
            self.pdnsutil("delete-zone", domain, check=False)
            self.pdnsutil("create-zone", domain, f"ns.{domain}")

            serial = str(int(time.time()))
            soa = f"ns.{domain} hostmaster.{domain} {serial} 3600 900 604800 300"
            self.replace_rrset(domain, ".", "SOA", "3600", soa)
            self.replace_rrset(domain, ".", "NS", "3600", f"ns.{domain}.")
            self.replace_rrset(domain, ".", "A", "3600", ip)
            self.replace_rrset(domain, "ns", "A", "3600", dns_ip)

            # AAAA (domain -> container IPv6, if available)
            ipv6 = d.get("ipv6")
            if ipv6:
                self.replace_rrset(domain, ".", "AAAA", "3600", ipv6)
                self.out.print(f"    zone reset: SOA, NS, A, AAAA  ({ip}, {ipv6})")
            else:
                # Remove any stale AAAA record
                self.pdnsutil("delete-rrset", domain, ".", "AAAA", check=False)
                self.out.print(f"    zone reset: SOA, NS, A  ({ip}, IPv4-only)")

        self.restart_services()

    def set_dns_records(self, zone, text):
        # Ensure zone exists or load-zone will fail
        self.pdnsutil("create-zone", zone, f"ns.{zone}", check=False)

        # PowerDNS load-zone usually expects a SOA and NS record at the apex.
        # It also needs a glue record (A) for the nameserver itself.
        if "SOA" not in text:
            self.wait_ready()
            serial = str(int(time.time()))
            soa = f"{zone}. 3600 IN SOA ns.{zone}. hostmaster.{zone}. {serial} 3600 900 604800 300\n"
            ns = f"{zone}. 3600 IN NS ns.{zone}.\n"
            glue = f"ns.{zone}. 3600 IN A {self.ipv4}\n"
            text = soa + ns + glue + text

        # Push content to container and load into PowerDNS
        self.incus.run(
            ["exec", self.name, "--", "bash", "-c", "cat > /tmp/zonefile"],
            input=text,
        )
        self.pdnsutil("load-zone", zone, "/tmp/zonefile")
        self.restart_services()
